CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competitionId` varchar(64) NOT NULL,
	`paymentId` varchar(64) NOT NULL,
	`participantName` text NOT NULL,
	`peopleCount` varchar(32) DEFAULT '1',
	`genre` text NOT NULL,
	`ageCategory` varchar(64),
	`nomination` text NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(64) NOT NULL,
	`institutionName` text,
	`institutionAddress` text,
	`directorName` text,
	`performanceTitle` text,
	`collectiveInfo` text,
	`videoLink1` text NOT NULL,
	`videoLink2` text,
	`amount` int NOT NULL,
	`status` enum('pending_payment','paid','accepted','rejected') NOT NULL DEFAULT 'pending_payment',
	`paymentDetails` json,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `applications_paymentId_unique` UNIQUE(`paymentId`)
);
--> statement-breakpoint
CREATE TABLE `competitions` (
	`id` varchar(64) NOT NULL,
	`code` varchar(128) NOT NULL,
	`title` text NOT NULL,
	`subtitle` text,
	`seasonBadge` varchar(128),
	`startDate` varchar(32) NOT NULL,
	`endDate` varchar(32) NOT NULL,
	`priceRegular` int NOT NULL DEFAULT 1700,
	`priceDiscount` int NOT NULL DEFAULT 1300,
	`priceReduced` int NOT NULL DEFAULT 790,
	`bannerUrl` text,
	`leadParagraph` text,
	`aboutText` text,
	`noticeText` text,
	`rulesSections` json,
	`faqs` json,
	`results` json,
	`paykeeperConfig` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
